HOST: http://www.google.com/

--- XO Membership API ---

---
Membership API will make a correct use of HTTP Response Status Codes and the response body will be JSON formatted   
Example of response payload when errors are detected on the API side:
---

--
Hello call
This is how you call the hello api
--

List products added into your shopping-cart. (comment block again in Markdown)
GET /
< 200
< Content-Type: application/json
Hello World


