HOST: http://www.google.com/

--- XO Membership API ---

---
Membership API will make a correct use of HTTP Response Status Codes and the response body will be JSON formatted.
---

--
Example    
This is an example of the response when errors are detected on the API side:
--

List products added into your shopping-cart. (comment block again in Markdown)
GET /
< 200
< Content-Type: application/json
Hello World


